#!/bin/bash
defaults write com.apple.dock scroll-to-open -bool true # Use your touchpad or mouse scroll wheel to interact with Dock items. Allows you to use an upward scrolling gesture to open stacks. Using the same gesture on applications that are running invokes Exposé/Mission Control.
killall Dock
